version: "3"

services:



  redis:
    image: redis:6.2.6
    container_name: redis
    restart: always
    privileged: true
    volumes:
      - ./data/redis/conf:/usr/local/etc/redis/
      - ./data/redis/data:/data
    expose:
      - 6379
    command:
      redis-server


  postgres:
    image: postgres
    container_name: pgsql
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: hoj
      TZ: Asia/Shanghai
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
    privileged: true
    expose:
      - 5432

  judger:
    image: hzcool/ubuntu-judger:v2
    restart: always
    container_name: rust-judger
    environment:
      - ACCESS_TOKEN=${JUDGE_ACCESS_TOKEN}
      - ADDR=${JUDGE_ADDR}
      - TEST_CASE_DIR=${TEST_CASE_DIR}
    volumes:
      - ./data/test_case:${TEST_CASE_DIR}
    privileged: true
    expose:
      - 7777

  rust-hoj:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust-hoj
    image: hoj:v1
    restart: always
    privileged: true
    volumes:
      - ./data/test_case:${TEST_CASE_DIR}
    links:
      - postgres
      - redis
      - judger
    depends_on:
      - postgres
      - redis
      - judger
    command:
      - /bin/bash
      - -c
      - |
        cd /src
        ./rust-hoj
    ports:
      - ${ADDR_PORT}:1881
